### ISSUE TITLE
Nested rules

### ISSUE THREAD

**Issue by spacemeowx2** [rabbit-digger/rabbit-digger#23]
Add nested rules like `or`, `and` to support complex rules.

Example:

```yaml
rule:
  - type: domain
    method: suffix
    domain: google.com
    and:
      - type: port
        port: 443
    target: proxy
```
